spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/ademgalitekin
    username: ademgalitekin
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8095

management:
  server:
    ssl:
      enabled: false
  endpoints:
    shutdown:
      enabled: true
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: httptrace,health,info,prometheus,metrics,env,scheduledtasks
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
      sensitive: false
      db:
        enabled: true
      defaults:
        enabled: true
    endpoint:
      health:
        show-details: always
        probes:
          enabled: true
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: coin_crawler
    description: Coin Crawler Microservice
    profile: prod
    version: 1.0.0

build:
  version: "1.0"

coin_crawler:
  message: "Coin Crawler PROD"